# Generated by Django 4.2 on 2023-06-03 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
